[build]
  command = "flutter build web --release"

[build.environment]
  FLUTTER_VERSION = "3.13.2"

[context.production]
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200