name: livework_view
description: A real-time task and hazard tracking system

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.1
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.4.0
  firebase_auth: ^4.8.0
  flutter_spinkit: 5.1.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.4.0

  # State Management
  provider: ^6.0.5

  # Image Handling
  image_picker: ^1.0.2
  file_picker: ^5.0.0
  http: ^1.1.0
  image: ^4.1.4
  cross_file: ^0.3.3

  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  file_saver: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/company_map.png
    - assets/images/logo.png